bitcamp-wasd/secret-back

- gateway/src/main/java/com/example/gateway/GatewayApplication.java
- gateway/src/main/resources/application.yml
- video/build.gradle
- video/src/main/java/com/example/video/config/S3ClientConfig.java
- video/src/main/java/com/example/video/controller/TestController.java
- video/src/main/java/com/example/video/controller/UploadController.java
- video/src/main/java/com/example/video/dto/VideoRegisterDto.java
- video/src/main/java/com/example/video/entity/Category.java
- video/src/main/java/com/example/video/entity/Post.java
- video/src/main/java/com/example/video/entity/PostComment.java
- video/src/main/java/com/example/video/entity/PostLikeList.java
- video/src/main/java/com/example/video/entity/SheetMusic.java
- video/src/main/java/com/example/video/entity/Video.java
- video/src/main/java/com/example/video/entity/state/VideoState.java
- video/src/main/java/com/example/video/repository/CategoryRepository.java
- video/src/main/java/com/example/video/repository/PostCommentRepository.java
- video/src/main/java/com/example/video/repository/PostLikeListRepository.java
- video/src/main/java/com/example/video/repository/PostRepository.java
- video/src/main/java/com/example/video/repository/VideoRepository.java
- video/src/main/java/com/example/video/service/UploadService.java
- video/src/main/java/com/example/video/util/Util.java
- video/src/main/resources/application.yml
- video/src/test/java/com/example/video/config/S3ClientConfigTest.java
> 게이트웨어 설정 변경, 비디오 서비스 엔티티 생성

- user/src/main/java/com/example/user/entity/UserEntity.java
- user/src/main/java/com/example/user/entity/UserRankEntity.java
- user/src/main/java/com/example/user/repository/UserRankRepository.java
- user/src/main/java/com/example/user/repository/UserRepository.java
- user/src/main/java/com/example/user/service/UserService.java
- user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
- user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
> 마이페이지 랭크 포인트 구현

- user/src/main/java/com/example/user/config/WebSecurityConfig.java
- user/src/main/java/com/example/user/controller/UserController.java
- user/src/main/java/com/example/user/dto/UpdateUserInfoDto.java
- user/src/main/java/com/example/user/dto/UserInfoDto.java
- user/src/main/java/com/example/user/entity/UserEntity.java
- user/src/main/java/com/example/user/service/UserService.java
- user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
내정보 보여주기 수정하기 + OAuth2 부분 로그인 기능 추가 소셜로그인 비밀번호 암호화 등록 수정
> 마이페이지 내정보 보여주기 수정하기 구현

- user/src/main/java/com/example/user/controller/UserController.java
- user/src/main/java/com/example/user/dto/UserInfoBannerDto.java
- user/src/main/java/com/example/user/dto/UserInfoDto.java
- user/src/main/java/com/example/user/service/UserService.java
> 마이페이지 내정보 보여주기 수정하기 수정및 배너부분 추가

- user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
- user/src/main/java/com/example/user/controller/AuthController.java
- user/src/main/java/com/example/user/controller/UserController.java
- user/src/main/java/com/example/user/entity/CustomOAuth2User.java
- user/src/main/java/com/example/user/filter/JwtAuthenticationFilter.java
- user/src/main/java/com/example/user/provider/JwtProvider.java
- user/src/main/java/com/example/user/service/UserService.java
- user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
email 로 검증받는걸 userId로 변환 + 레디스에 email 대신 userId+role 담기
> email -> userId + role 레디스에 담기 + email 검증 -> userId변환

- user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
- user/src/main/java/com/example/user/controller/AuthController.java
- user/src/main/java/com/example/user/entity/CustomOAuth2User.java
- user/src/main/java/com/example/user/filter/JwtAuthenticationFilter.java
- user/src/main/java/com/example/user/provider/JwtProvider.java
- user/src/main/java/com/example/user/service/UserService.java
- user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
- user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
> userEntity -> oAuth2User 버그 픽스

- user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
- user/src/main/java/com/example/user/controller/AuthController.java
- user/src/main/java/com/example/user/filter/JwtAuthenticationFilter.java
- user/src/main/java/com/example/user/filter/TokenUtils.java
- user/src/main/java/com/example/user/service/RedisService.java
- user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
key accessToken value userId,role 담기
> key accessToken value userId,role 담기

- user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
- user/src/main/java/com/example/user/config/WebSecurityConfig.java
- user/src/main/java/com/example/user/controller/AuthController.java
- user/src/main/java/com/example/user/entity/CustomOAuth2User.java
- user/src/main/java/com/example/user/filter/JwtAuthenticationFilter.java
- user/src/main/java/com/example/user/provider/JwtProvider.java
- user/src/main/java/com/example/user/service/RedisService.java
- user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
- user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
redis nickname 담기 oauth2 리다이렉트 경로 수정
> redis nickname 담기 oauth2 리다이렉트 수정

- gateway/src/main/java/com/example/gateway/config/RedisConfig.java
- gateway/src/main/java/com/example/gateway/filter/LoginFilter.java
- user/src/main/java/com/example/user/config/RedisConfig.java
- user/src/main/java/com/example/user/controller/AuthController.java
- user/src/main/java/com/example/user/service/RedisService.java
- video/src/main/java/com/example/video/controller/PostController.java
- video/src/main/java/com/example/video/controller/TestController.java
- video/src/main/java/com/example/video/entity/Post.java
- video/src/main/java/com/example/video/entity/Video.java
- video/src/main/java/com/example/video/global/annotation/HeaderUserAuthArgumentResolver.java
- video/src/main/java/com/example/video/global/config/Base64Config.java
- video/src/main/java/com/example/video/global/config/annotationConfig.java
- video/src/main/java/com/example/video/service/PostService.java
- video/src/main/resources/application.yml
> 로그인 헤더 base64 인코딩 후 디코딩(헤더에 한글 깨짐 문제 해결)

- user/src/main/java/com/example/user/annotation/HeaderUserAuth.java
- user/src/main/java/com/example/user/annotation/HeaderUserAuthArgumentResolver.java
- user/src/main/java/com/example/user/config/Base64Config.java
- user/src/main/java/com/example/user/config/annotationConfig.java
- user/src/main/java/com/example/user/controller/UserController.java
- user/src/main/java/com/example/user/dto/UserAuth.java
- video/src/main/java/com/example/video/controller/PostCommentController.java
- video/src/main/java/com/example/video/controller/PostController.java
- video/src/main/java/com/example/video/controller/PostLikeController.java
- video/src/main/java/com/example/video/entity/Video.java
- video/src/main/java/com/example/video/entity/VideoLikeList.java
- video/src/main/java/com/example/video/repository/PostLikeListRepository.java
- video/src/main/java/com/example/video/repository/VideoLikeListRepository.java
- video/src/main/java/com/example/video/service/PostLikeService.java
> 동영상 좋아요 기능

- user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
- user/src/main/java/com/example/user/controller/AuthController.java
- user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
> logout -> sign-out 변경

- battle/build.gradle
- battle/src/main/java/com/example/battle/entity/Battle.java
- battle/src/main/java/com/example/battle/entity/BattleComment.java
- battle/src/main/java/com/example/battle/entity/BattleVoteList.java
- battle/src/main/resources/application.properties
- battle/src/main/resources/mapper/battleMapper.xml
- user/src/main/java/com/example/user/controller/UserController.java
- user/src/main/java/com/example/user/dto/info/UserApiInfo.java
- user/src/main/java/com/example/user/service/UserService.java
> 배틀 진행중 + 유저 닉네임 랭크네임 정보 보내기

- battle/build.gradle
- battle/src/main/java/com/example/battle/config/MyBatisConfig.java
- battle/src/main/java/com/example/battle/controller/BattleController.java
- battle/src/main/java/com/example/battle/dto/BattleDto.java
- battle/src/main/java/com/example/battle/dto/CommentDto.java
- battle/src/main/java/com/example/battle/dto/info/PostDto.java
- battle/src/main/java/com/example/battle/dto/info/UserDto.java
- battle/src/main/java/com/example/battle/entity/Battle.java
- battle/src/main/java/com/example/battle/entity/BattleComment.java
- battle/src/main/java/com/example/battle/entity/BattleVoteList.java
- battle/src/main/java/com/example/battle/mapper/BattleMapper.java
- battle/src/main/java/com/example/battle/service/BattleCommentService.java
- battle/src/main/java/com/example/battle/service/BattleService.java
- battle/src/main/java/com/example/battle/service/BattleVoteService.java
- battle/src/main/resources/application.yml
- battle/src/main/resources/mapper/battleMapper.xml
> 배틀 상세보기 투표 댓글 댓글 페이지네이션

- battle/src/main/java/com/example/battle/annotation/HeaderUserAuthArgumentResolver.java
- battle/src/main/java/com/example/battle/api/VideoRestApi.java
- battle/src/main/java/com/example/battle/controller/BattleController.java
- battle/src/main/java/com/example/battle/mapper/BattleMapper.java
- battle/src/main/java/com/example/battle/service/BattleService.java
- battle/src/main/resources/mapper/battleMapper.xml
배틀 무한스크롤 방식 리스트 출력
추가 기능 작성 및 연결시 필요한 데이터 수정 필요
> 배틀 연결 방식 수정

- challenge/package.json
- challenge/src/app.module.ts
- challenge/src/auth/headers.decorator.ts
- challenge/src/auth/userAuth.dto.ts
- challenge/src/challenge/challenge.collection.ts
- challenge/src/challenge/challenge.controller.ts
- challenge/src/challenge/challenge.module.ts
- challenge/src/challenge/challenge.service.ts
- challenge/src/challenge/state.enum.ts
- challenge/src/challengeList/challengeList.collection.ts
- challenge/src/config/cloud.config.ts
- challenge/src/config/cloud.provider.ts
- challenge/src/config/eureka.config.ts
- challenge/src/main.ts
- challenge/src/module/config.module.ts
- challenge/src/module/mongo.module.ts
- challenge/yarn.lock
Nest.js와 Spring Cloud 서비스 연결
Naver Cloud Mongodb 연결
> challenge 설정

- battle/src/main/java/com/example/battle/api/VideoRestApi.java
- battle/src/main/java/com/example/battle/controller/BattleController.java
- battle/src/main/java/com/example/battle/dto/BattleRegisterDto.java
- battle/src/main/java/com/example/battle/dto/post/response/PostIdDto.java
- battle/src/main/java/com/example/battle/mapper/BattleMapper.java
- battle/src/main/java/com/example/battle/service/BattleCommentService.java
- battle/src/main/java/com/example/battle/service/BattleService.java
- battle/src/main/java/com/example/battle/service/BattleVoteService.java
- battle/src/main/resources/mapper/battleMapper.xml
> 배틀 등록 투표 확인 체크 기능 추가

- battle/src/main/java/com/example/battle/dto/BattleDto.java
- battle/src/main/java/com/example/battle/dto/CommentDto.java
- battle/src/main/java/com/example/battle/entity/Battle.java
- battle/src/main/java/com/example/battle/entity/BattleComment.java
- battle/src/main/java/com/example/battle/service/BattleCommentService.java
- battle/src/main/java/com/example/battle/service/BattleService.java
- battle/src/main/resources/mapper/battleMapper.xml
> 날짜 localDate -> localDateTime 수정

- battle/src/main/java/com/example/battle/BattleApplication.java
- battle/src/main/java/com/example/battle/api/UserRestApi.java
- battle/src/main/java/com/example/battle/api/VideoRestApi.java
- battle/src/main/java/com/example/battle/controller/BattleController.java
- battle/src/main/java/com/example/battle/dto/post/response/PostUserIdDto.java
- battle/src/main/java/com/example/battle/mapper/BattleMapper.java
- battle/src/main/java/com/example/battle/service/BattleService.java
- battle/src/main/resources/mapper/battleMapper.xml
- user/src/main/java/com/example/user/controller/UserController.java
- user/src/main/java/com/example/user/service/UserService.java
> 배틀 종료시 포인트 적용 및 상태 종료 변경

- battle/src/main/java/com/example/battle/dto/BattleDto.java
- battle/src/main/java/com/example/battle/service/BattleService.java
> 배틀 게시판 삭제 위한 dto 추가

- battle/src/main/java/com/example/battle/controller/BattleController.java
- battle/src/main/java/com/example/battle/dto/response/BattleMyCommentDto.java
- battle/src/main/java/com/example/battle/mapper/BattleMapper.java
- battle/src/main/java/com/example/battle/service/BattleCommentService.java
- battle/src/main/resources/mapper/battleMapper.xml
- user/build.gradle
- user/src/main/java/com/example/user/UserApplication.java
- user/src/main/java/com/example/user/api/BattleRestApi.java
- user/src/main/java/com/example/user/controller/UserController.java
- user/src/main/java/com/example/user/dto/battle/response/BattleMyCommentDto.java
- user/src/main/java/com/example/user/service/UserService.java
> 마이페이지 댓글 리스트 및 삭제

- user/src/main/java/com/example/user/controller/UserController.java
- user/src/main/java/com/example/user/dto/info/request/UserIdRequestDto.java
- user/src/main/java/com/example/user/dto/info/response/UserApiInfo.java
- user/src/main/java/com/example/user/dto/info/response/UserListDto.java
- user/src/main/java/com/example/user/dto/info/response/UserRankInfo.java
- user/src/main/java/com/example/user/repository/UserRepository.java
- user/src/main/java/com/example/user/service/UserService.java
> 유저 아이디 리스트 입력시 해당 정보리스트 출력

- battle/src/main/java/com/example/battle/controller/BattleController.java
- battle/src/main/java/com/example/battle/dto/CommentDto.java
- battle/src/main/java/com/example/battle/dto/battle/request/BattleCommentListDto.java
- battle/src/main/java/com/example/battle/service/BattleCommentService.java
- battle/src/main/resources/mapper/battleMapper.xml
- user/src/main/java/com/example/user/repository/UserRepository.java
> 마이페이지 배틀댓글 리스트 선택삭제 수정

- battle/src/main/java/com/example/battle/controller/BattleController.java
- battle/src/main/java/com/example/battle/mapper/BattleMapper.java
- battle/src/main/java/com/example/battle/service/BattleService.java
- battle/src/main/resources/mapper/battleMapper.xml
restapi 리팩토링 myComments -> mycomment
> 해당 동영상 게시물 없을 시 배틀 null 업데이트 후 게시글 삭제 예외처리

- challenge/src/config/cloud.provider.ts
spring cloud config에서 main브랜치에서 설정정보를 가져오는 것에서 prod 브랜치에서 설정을 가져오도록 변경
> Update cloud.provider.ts 
